version: '3.8'
services:
  test-app:
    image: test-app:local
    container_name: test-app-container
    ports:
      - "8080:8080"
    environment:
      # Docker Compose akan mengambil nilai dari environment shell saat runtime
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
